Algoritmo "variaveis"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Cleison Melo
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/04/2020
Var
// Seção de Declarações das variáveis 
   primeiroNome, segundoNome, cidade, endereco: caractere
   idade: inteiro
   
   
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo